import type { Metadata } from "next";
import {
  Poppins as SansFont,
  Playfair_Display as SerifFont,
} from "next/font/google";
import "./globals.css";

const sansFont = SansFont({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sans",
});
const serifFont = SerifFont({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${sansFont.variable} ${serifFont.variable}`} lang="en">
      <body>{children}</body>
    </html>
  );
}
